defaultPortal: FirstSite
portals:
  - name: FirstSite
    portalId: 22495181
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKqz3NKoMBIJAA0AAAAA4A0DGM3_3Aog1uqQFiju6QwyFKqW-XAQvLIFmfmui0hMSTxODZYvOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhSgIcPlY6yaSp1WIwwCeeZeus3tR0oDbmExUgBaAA
        expiresAt: '2022-08-11T00:39:00.271Z'
    personalAccessKey: >-
      CiRjMTM3Nzc3Ny0xNWRhLTRhYjAtYTAzMS0yOTg5ZDRmMGMzZDQQzf_cChjW6pAWKhkABeaRgv4o15mGeY0boLqv2td-vUhyu2ZoSgNuYTE
